import QtQuick 2.15
import QtTest 1.15
import "qrc:/qml/utils/format.js" as Format

// The three rules standing between a hostile message and the email
// renderer: the Content-Security-Policy handed to loadHtml(), the
// HTML-vs-plain-text decision, and escapeHtml().
//
// These live in utils/format.js rather than EmailDetail.qml precisely so
// this file can reach them -- EmailDetail needs QtWebEngine and the whole
// com.kysecurity.mail singleton graph to instantiate, which is why the rules
// inside it went untested long enough to grow the two bugs below.
TestCase {
    name: "EmailBodyRendering"

    // ---- Content-Security-Policy ----------------------------------------

    function test_csp_denies_everything_by_default() {
        var csp = Format.emailContentSecurityPolicy(false)
        verify(csp.indexOf("default-src 'none'") !== -1)
        verify(csp.indexOf("script-src 'none'") !== -1)
        verify(csp.indexOf("frame-src 'none'") !== -1)
        verify(csp.indexOf("object-src 'none'") !== -1)
        verify(csp.indexOf("connect-src 'none'") !== -1)
        verify(csp.indexOf("form-action 'none'") !== -1)
        verify(csp.indexOf("base-uri 'none'") !== -1)
    }

    // The tracking-pixel case: with images off, no remote image origin is
    // reachable at all. data: stays allowed so an inline image in a
    // legitimately self-contained message still renders.
    function test_csp_forbids_remote_images_until_opted_in() {
        var csp = Format.emailContentSecurityPolicy(false)
        verify(csp.indexOf("img-src data:;") !== -1)
        verify(csp.indexOf("img-src http:") === -1)
    }

    function test_csp_allows_remote_images_once_opted_in() {
        var csp = Format.emailContentSecurityPolicy(true)
        verify(csp.indexOf("img-src http: https: data:;") !== -1)
        // Opting in to images must not widen anything else -- same rule the
        // interceptor enforces (RemoteContentInterceptorTest).
        verify(csp.indexOf("media-src 'none'") !== -1)
        verify(csp.indexOf("font-src 'none'") !== -1)
        verify(csp.indexOf("frame-src 'none'") !== -1)
    }

    // sandbox is ignored when CSP is delivered by <meta>, which is the only
    // channel loadHtml() has. Claiming it would be claiming a control that
    // does not exist.
    function test_csp_does_not_claim_a_sandbox_it_cannot_enforce() {
        verify(Format.emailContentSecurityPolicy(true).indexOf("sandbox") === -1)
    }

    // ---- HTML vs plain text ---------------------------------------------

    function test_real_html_bodies_are_treated_as_html() {
        verify(Format.looksLikeHtmlDocument("<html><body>hi</body></html>"))
        verify(Format.looksLikeHtmlDocument("<!DOCTYPE html>\n<html><body>hi</body></html>"))
        verify(Format.looksLikeHtmlDocument("  \n\t<div>hi</div>"))
        verify(Format.looksLikeHtmlDocument("<!-- generated by a mailer -->\n<table><tr><td>hi"))
        verify(Format.looksLikeHtmlDocument("<P>SHOUTING MAILER</P>"))
    }

    // The bug this rule replaced. The old sniff matched any of seventeen tag
    // names ANYWHERE in the body, so a plain-text message that merely quoted
    // markup was rendered as live HTML -- and the quoted <img> became a real
    // fetch the moment the user pressed "Show images".
    function test_plain_text_quoting_markup_is_not_html() {
        verify(!Format.looksLikeHtmlDocument(
            "Hi, the bug is that we emit <img src=\"https://tracker.example/p.gif\"> in the footer."))
        verify(!Format.looksLikeHtmlDocument("Use <br> for a line break."))
        verify(!Format.looksLikeHtmlDocument("See the <table> element docs."))
        verify(!Format.looksLikeHtmlDocument(""))
        verify(!Format.looksLikeHtmlDocument("plain sentence, no markup at all"))
    }

    // Misclassifying HTML as text renders visible markup: ugly, and inert.
    // Misclassifying text as HTML fetches. When the guess is wrong, it must
    // be wrong in the first direction.
    function test_ambiguous_bodies_fall_back_to_escaped_text() {
        var body = "Not markup until later: <div>"
        verify(!Format.looksLikeHtmlDocument(body))
        var html = Format.renderedEmailHtml(body, true, "")
        verify(html.indexOf("<pre>") !== -1)
        verify(html.indexOf("&lt;div&gt;") !== -1)
    }

    // ---- escaping --------------------------------------------------------

    function test_escape_html_covers_quotes_too() {
        compare(Format.escapeHtml("a<b>&\"c\"'d'"), "a&lt;b&gt;&amp;&quot;c&quot;&#39;d&#39;")
    }

    // ---- assembled document ---------------------------------------------

    function test_rendered_document_carries_the_policy_before_any_content() {
        var html = Format.renderedEmailHtml("<html><body>x</body></html>", false, "body{}")
        var cspAt = html.indexOf("Content-Security-Policy")
        var bodyAt = html.indexOf("<body>")
        verify(cspAt !== -1)
        verify(cspAt < bodyAt)
        // ...and before the <style> block, which is itself content that can
        // reference a URL.
        verify(cspAt < html.indexOf("<style>"))
    }
}
